### PR TITLE
Remove "android:allowBackup"

### PR DESCRIPTION
**Pull request by ejohansson**
Removed "android:allowBackup" in order to use custom value.

### CODE REVIEW

**Comment by ejohansson** [comment]
Please remove this so that we don't have to use `tools:replace="android:allowBackup"`.

**Comment by Aimisue1987** [comment]
I will try and accept

**Review by Aimisue1987 — APPROVED** [review]

**Review by mtsibulski — APPROVED** [review]

**Review by msilva-tillster — APPROVED** [review]

**Review by nickkotillster — APPROVED** [review]

**Comment by nickkotillster** [comment]
Thanks for getting this merged @amimishr. Was curious if you could provide an update of when this would get published

**Comment by amimishr** [comment]
@nickkotillster Since The PR has already been merged, curious to understand what do you actually mean by "would get published"?

**Comment by msilva-tillster** [comment]
@amimishr
You should release a new version and create a new tag.

**Comment by amimishr** [comment]
@msilva-tillster , let me check internally on the that part.

**Comment by joel-oliveira** [comment]
> @msilva-tillster , let me check internally on the that part.

@amimishr do you have any date for the updated SDK version?
This is blocking us from doing an integration with Authorize.Net.

**Comment by joel-oliveira** [comment]
Hi @amimishr even with the PR merged, in the releases page (https://github.com/AuthorizeNet/accept-sdk-android/releases) we are missing a new release with the PR. Can you please publish a new release? Thanks.

**Comment by amimishr** [comment]
@joel-oliveira , To make a release(does not matter the triviality of the change), we have to go through the security architecture review process. We will make the release as soon as we get a go ahead from our security team.

**Comment by joel-oliveira** [comment]
> @joel-oliveira , To make a release(does not matter the triviality of the change), we have to go through the security architecture review process. We will make the release as soon as we get a go ahead from our security team.

@amimishr we understand that. We need this new updated SDK to submit the app (with the integration) to be assessed by our security team. For planning purposes, do you have any ETA for release? This is on the critical path in our project. If not resolved by the end of this week, we may be forced to drop Authorize.Net integration.

**Comment by amimishr** [comment]
@joel-oliveira , We have submitted the build for the security testing, if there are no blockers we are expecting the go ahead by Friday EOD central time. Hope that helps.

**Comment by joel-oliveira** [comment]
> @joel-oliveira , We have submitted the build for the security testing, if there are no blockers we are expecting the go ahead by Friday EOD central time. Hope that helps.

Thanks @amimishr . We will wait then for the updated release.

**Comment by msilva-tillster** [comment]
@amimishr
Any news on the build that was supposed to be delivered on friday?

**Comment by joel-oliveira** [comment]
Hi @amimishr! Friendly reminder. Do you have any update on the release date? As I said before, this is preventing us from integrating with Authorize.Net due to security reasons. Thanks in advance.

**Comment by amimishr** [comment]
@joel-oliveira I have reached the security team again for their status updates, will do the needful ASAP.

**Comment by amimishr** [comment]
@joel-oliveira , @msilva-tillster I have published the new version, please check the same.

**Comment by msilva-tillster** [comment]
@amimishr Awesome. I was trying to get the repo dependency directly from the new tag created using jitpack and unfortunately I'm having problems getting it.
Can you also update the jcenter version to 1.0.3?

**Comment by amimishr** [comment]
@msilva-tillster Currently I do not have the credentials to do that. I need to look for someone who did it earlier. This might take some time.

**Pull request merged**
